require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ResearchItemsController do

  # This should return the minimal set of attributes required to create a valid
  # ResearchItem. As you add validations to ResearchItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all research_items as @research_items" do
      research_item = ResearchItem.create! valid_attributes
      get :index
      assigns(:research_items).should eq([research_item])
    end
  end

  describe "GET show" do
    it "assigns the requested research_item as @research_item" do
      research_item = ResearchItem.create! valid_attributes
      get :show, :id => research_item.id.to_s
      assigns(:research_item).should eq(research_item)
    end
  end

  describe "GET new" do
    it "assigns a new research_item as @research_item" do
      get :new
      assigns(:research_item).should be_a_new(ResearchItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested research_item as @research_item" do
      research_item = ResearchItem.create! valid_attributes
      get :edit, :id => research_item.id.to_s
      assigns(:research_item).should eq(research_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ResearchItem" do
        expect {
          post :create, :research_item => valid_attributes
        }.to change(ResearchItem, :count).by(1)
      end

      it "assigns a newly created research_item as @research_item" do
        post :create, :research_item => valid_attributes
        assigns(:research_item).should be_a(ResearchItem)
        assigns(:research_item).should be_persisted
      end

      it "redirects to the created research_item" do
        post :create, :research_item => valid_attributes
        response.should redirect_to(ResearchItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved research_item as @research_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResearchItem.any_instance.stub(:save).and_return(false)
        post :create, :research_item => {}
        assigns(:research_item).should be_a_new(ResearchItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ResearchItem.any_instance.stub(:save).and_return(false)
        post :create, :research_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested research_item" do
        research_item = ResearchItem.create! valid_attributes
        # Assuming there are no other research_items in the database, this
        # specifies that the ResearchItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ResearchItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => research_item.id, :research_item => {'these' => 'params'}
      end

      it "assigns the requested research_item as @research_item" do
        research_item = ResearchItem.create! valid_attributes
        put :update, :id => research_item.id, :research_item => valid_attributes
        assigns(:research_item).should eq(research_item)
      end

      it "redirects to the research_item" do
        research_item = ResearchItem.create! valid_attributes
        put :update, :id => research_item.id, :research_item => valid_attributes
        response.should redirect_to(research_item)
      end
    end

    describe "with invalid params" do
      it "assigns the research_item as @research_item" do
        research_item = ResearchItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResearchItem.any_instance.stub(:save).and_return(false)
        put :update, :id => research_item.id.to_s, :research_item => {}
        assigns(:research_item).should eq(research_item)
      end

      it "re-renders the 'edit' template" do
        research_item = ResearchItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ResearchItem.any_instance.stub(:save).and_return(false)
        put :update, :id => research_item.id.to_s, :research_item => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested research_item" do
      research_item = ResearchItem.create! valid_attributes
      expect {
        delete :destroy, :id => research_item.id.to_s
      }.to change(ResearchItem, :count).by(-1)
    end

    it "redirects to the research_items list" do
      research_item = ResearchItem.create! valid_attributes
      delete :destroy, :id => research_item.id.to_s
      response.should redirect_to(research_items_url)
    end
  end

end
